/* This file was generated by `qmk generate-config-h`. Do not edit or copy.
 */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION gmmk/pro/ansi
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER Glorious
#endif // MANUFACTURER

#ifndef PRODUCT
#   define PRODUCT GMMK Pro
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x5044
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x320F
#endif // VENDOR_ID

#ifndef QMK_KEYS_PER_SCAN
#   define QMK_KEYS_PER_SCAN 4
#endif // QMK_KEYS_PER_SCAN

#ifndef TAP_CODE_DELAY
#   define TAP_CODE_DELAY 10
#endif // TAP_CODE_DELAY

#ifndef USB_POLLING_INTERVAL_MS
#   define USB_POLLING_INTERVAL_MS 1
#endif // USB_POLLING_INTERVAL_MS

#ifndef MATRIX_COLS
#   define MATRIX_COLS 8
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { A0, A1, A2, A3, A4, A8, A9, A10 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 11
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { B0, B1, B2, B3, B4, B5, B6, B7, B8, B9, B10 }
#endif // MATRIX_ROW_PINS
